## Data Preprocessing for Machine Learning
### Training Data

In [4]:
# imports
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import joblib

In [5]:
raw_data_train = pd.read_csv('../data/Train.csv')
raw_data_train.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,Cat_4,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,Cat_4,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,Cat_6,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,Cat_6,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,Cat_6,A

In [16]:
# Encoding categorical variables
copy_data=raw_data_train.__deepcopy__()
ge=LabelEncoder()
em=LabelEncoder()
gr=LabelEncoder()
pr=LabelEncoder()
ss=LabelEncoder()
se=LabelEncoder()
va=LabelEncoder()
# Filling NA values with appropriate values
copy_data['Ever_Married'].fillna('No', inplace=True)
copy_data['Graduated'].fillna('No', inplace=True)
copy_data['Profession'].fillna('Other', inplace=True)
copy_data['Work_Experience'].fillna(0, inplace=True)
copy_data['Family_Size'].fillna(0, inplace=True)

copy_data['Gender'] = ge.fit_transform(copy_data['Gender'])
copy_data['Ever_Married'] = em.fit_transform(copy_data['Ever_Married'])
copy_data['Graduated'] = gr.fit_transform(copy_data['Graduated'])
copy_data['Profession'] = pr.fit_transform(copy_data['Profession'])
copy_data['Spending_Score'] = ss.fit_transform(copy_data['Spending_Score'])
copy_data['Segmentation'] = se.fit_transform(copy_data['Segmentation'])
copy_data['Var_1'] = va.fit_transform(copy_data['Var_1'])


# Saving the encoders
joblib.dump(ge, '../data/preprocessed_data/gender_encoder.pkl')
joblib.dump(em, '../data/preprocessed_data/married_encoder.pkl')
joblib.dump(gr, '../data/preprocessed_data/graduated_encoder.pkl')
joblib.dump(pr, '../data/preprocessed_data/profession_encoder.pkl')
joblib.dump(ss, '../data/preprocessed_data/spending_score_encoder.pkl')
joblib.dump(se, '../data/preprocessed_data/segmentation_encoder.pkl')
joblib.dump(va, '../data/preprocessed_data/var1_encoder.pkl')

C:\Users\caaka\AppData\Local\Temp\ipykernel_23964\27583246.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_data['Ever_Married'].fillna('No', inplace=True)
C:\Users\caaka\AppData\Local\Temp\ipykernel_23964\27583246.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_data['Graduated'].fillna('No', inplace=True)
C:\Users\caaka\AppData\Local\Temp\ipykernel_23964\27583246.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_data['Profession'].fillna('Other', inplace=True)
C:\Users\caaka\AppData\Local\Temp\ipykernel_23964\27583246.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_data['Work_Experience'].fillna(0, inplace=True)
C:\Users\caaka\AppData\Local\Temp\ipykernel_23964\27583246.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_data['Family_Size'].fillna(0, inplace=True)

['../data/preprocessed_data/var1_encoder.pkl']

In [7]:
copy_data

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,1,0,22,0,0,1.0,0,4.0,3,3
1,462643,0,1,38,1,4,0.0,2,3.0,3,0
2,466315,0,1,67,1,4,1.0,0,1.0,5,1
3,461735,1,1,67,1,4,0.0,1,2.0,5,1
4,462669,0,1,40,1,1,0.0,1,6.0,5,0
...,...,...,...,...,...,...,...,...,...,...,...
8063,464018,1,0,22,0,2,0.0,0,7.0,0,3
8064,464685,1,0,35,0,4,3.0,0,4.0,3,3
8065,465406,0,0,33,1,0,1.0,0,1.0,5,3
8066,467299,0,0,27,1,0,1.0,0,4.0,5,1
8067,461879,1,1,37,1,4,0.0,2,3.0,3,1

In [8]:
copy_data.isna().sum()

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
Segmentation       0
dtype: int64

In [9]:
# Dropping unnecessary columns
# important columns are: features=['Ever_Married', 'Age', 'Graduated', 'Profession', 'Family_Size','Spending_Score']

X_train=copy_data.drop(['Segmentation','ID','Gender','Work_Experience','Var_1'], axis=1)
y=copy_data['Spending_Score']

In [10]:
# Normalizing the data
scaler = StandardScaler()
X_train_norm=scaler.fit_transform(X_train)
X_train_norm = pd.DataFrame(X_train_norm, columns=X_train.columns)

# Saving the X_train data for later use
joblib.dump(X_train_norm,'../data/preprocessed_data/X_train_norm.pkl')

['../data/preprocessed_data/X_train_norm.pkl']

## Test Data

In [11]:
raw_data_test= pd.read_csv('../data/Test.csv')
raw_data_test

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,Female,Yes,36,Yes,Engineer,0.0,Low,1.0,Cat_6,B
1,458994,Male,Yes,37,Yes,Healthcare,8.0,Average,4.0,Cat_6,A
2,458996,Female,Yes,69,No,NaN,0.0,Low,1.0,Cat_6,A
3,459000,Male,Yes,59,No,Executive,11.0,High,2.0,Cat_6,B
4,459001,Female,No,19,No,Marketing,NaN,Low,4.0,Cat_6,A
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,Male,No,29,No,Healthcare,9.0,Low,4.0,Cat_6,B
2623,467958,Female,No,35,Yes,Doctor,1.0,Low,1.0,Cat_6,A
2624,467960,Female,No,53,Yes,Entertainment,NaN,Low,2.0,Cat_6,C
2625,467961,Male,Yes,47,Yes,Executive,1.0,High,5.0,Cat_4,C
2626,467968,Female,No,43,Yes,Healthcare,9.0,Low,3.0,Cat_7,A

In [12]:
raw_data_test.isna().sum()

ID                   0
Gender               0
Ever_Married        50
Age                  0
Graduated           24
Profession          38
Work_Experience    269
Spending_Score       0
Family_Size        113
Var_1               32
Segmentation         0
dtype: int64

In [13]:
copy_test_data=raw_data_test.__deepcopy__()
# Filling NA values with appropriate values
copy_test_data['Ever_Married'].fillna('No', inplace=True)
copy_test_data['Graduated'].fillna('No', inplace=True)
copy_test_data['Profession'].fillna('Other', inplace=True)
copy_test_data['Work_Experience'].fillna(0, inplace=True)
copy_test_data['Family_Size'].fillna(0, inplace=True)

# Encoding categorical variables
le = LabelEncoder()
copy_test_data['Gender'] = le.fit_transform(copy_test_data['Gender'].map({'Male': 1, 'Female' : 0}))
copy_test_data['Ever_Married'] = le.fit_transform(copy_test_data['Ever_Married'].map({'Yes': 1, 'No' : 0}))
copy_test_data['Graduated'] = le.fit_transform(copy_test_data['Graduated'].map({'Yes': 1, 'No' : 0}))
copy_test_data['Profession'] = le.fit_transform(copy_test_data['Profession'].map({'Healthcare': 0, 'Entertainment' : 1, 'Other' : 2, 'Academic' : 3, 'Artist' : 4, 'Sports' : 5}))
copy_test_data['Spending_Score'] = le.fit_transform(copy_test_data['Spending_Score'].map({'Low': 0, 'Medium' : 1, 'High' : 2}))
copy_test_data['Segmentation'] = le.fit_transform(copy_test_data['Segmentation'].map({'A': 0, 'B' : 1, 'C' : 2, 'D' : 3}))
copy_test_data['Var_1'] = le.fit_transform(copy_test_data['Var_1'].map({'Cat_1': 0, 'Cat_2' : 1, 'Cat_3' : 2, 'Cat_4' : 3, 'Cat_5' : 4, 'Cat_6' : 5, 'Cat_7' : 6, 'Cat_8' : 7, 'Cat_9' : 8}))

C:\Users\caaka\AppData\Local\Temp\ipykernel_23964\3177554247.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_test_data['Ever_Married'].fillna('No', inplace=True)
C:\Users\caaka\AppData\Local\Temp\ipykernel_23964\3177554247.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_test_data['Graduated'].fillna('No', inplace=True)
C:\Users\caaka\AppData\Local\Temp\ipykernel_23964\3177554247.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_test_data['Profession'].fillna('Other', inplace=True)
C:\Users\caaka\AppData\Local\Temp\ipykernel_23964\3177554247.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_test_data['Work_Experience'].fillna(0, inplace=True)
C:\Users\caaka\AppData\Local\Temp\ipykernel_23964\3177554247.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_test_data['Family_Size'].fillna(0, inplace=True)

In [14]:
copy_test_data.isnull().sum()

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
Segmentation       0
dtype: int64

In [15]:
# Dropping unnecessary columns
X_test=copy_test_data.drop(['Segmentation','ID','Gender','Work_Experience','Var_1'], axis=1)
y=copy_test_data['Spending_Score']

# Normalizing the data
scaler = StandardScaler()
X_test_norm=scaler.fit_transform(X_test)
X_test_norm = pd.DataFrame(X_test_norm, columns=X_test.columns)

joblib.dump(scaler,'../data/preprocessed_data/scaler.pkl')
# Saving the scaler for later use

# Saving the X_test data for later use
joblib.dump(X_test_norm,'../data/preprocessed_data/X_test_norm.pkl')

['../data/preprocessed_data/X_test_norm.pkl']